"""schema inicial

Revision ID: 3f1f10825b1b
Revises: 
Create Date: 2026-08-23 12:27:24.144792
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3f1f10825b1b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('razao_social', sa.Text(), nullable=False),
    sa.Column('nome_fantasia', sa.Text(), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('tipo', sa.Enum('embarcador', 'transportadora', 'ambos', 'plataforma', name='tipo_empresa'), nullable=False),
    sa.Column('retencao_meses', sa.Integer(), server_default='60', nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa')),
    sa.UniqueConstraint('cnpj', name=op.f('uq_empresa_cnpj'))
    )
    op.create_index('ix_empresa_ativa', 'empresa', ['ativa'], unique=False, postgresql_where=sa.text('ativa IS true'))
    op.create_table('destinatario_alerta',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('papel', sa.Enum('operador', 'gestor', 'admin', name='papel_usuario'), nullable=True),
    sa.Column('gravidade_minima', sa.Enum('alerta', 'acao', 'critica', name='gravidade'), server_default='alerta', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_destinatario_alerta_empresa_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destinatario_alerta')),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_destinatario_empresa_email')
    )
    op.create_table('perfil_termico',
    sa.Column('codigo', sa.String(length=48), nullable=False),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rotulo', sa.Text(), nullable=False),
    sa.Column('min_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('alerta_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('alerta_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tolerancia_segundos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tor_max_segundos', sa.Integer(), nullable=True),
    sa.Column('mkt_limite_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_c < max_c', name=op.f('ck_perfil_termico_faixa_coerente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_perfil_termico_empresa_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perfil_termico')),
    sa.UniqueConstraint('codigo', 'versao', name='uq_perfil_termico_codigo_versao')
    )
    op.create_index('ix_perfil_termico_empresa_id', 'perfil_termico', ['empresa_id'], unique=False)
    op.create_table('usuario',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('papel', sa.Enum('operador', 'gestor', 'admin', name='papel_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ultimo_login_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_usuario_empresa_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_index('ix_usuario_empresa_id', 'usuario', ['empresa_id'], unique=False)
    op.create_table('arquivo',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('nome_original', sa.Text(), nullable=False),
    sa.Column('caminho', sa.Text(), nullable=False),
    sa.Column('tipo_mime', sa.String(length=128), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('categoria', sa.Enum('laudo', 'evidencia', 'certificado', name='categoria_arquivo'), nullable=False),
    sa.Column('enviado_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_arquivo_empresa_id')),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuario.id'], name=op.f('fk_arquivo_enviado_por')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arquivo'))
    )
    op.create_index('ix_arquivo_empresa_categoria', 'arquivo', ['empresa_id', 'categoria'], unique=False)
    op.create_index('ix_arquivo_sha256', 'arquivo', ['sha256'], unique=False)
    op.create_table('chave_idempotencia',
    sa.Column('chave', sa.String(length=160), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('resposta_status', sa.Integer(), nullable=True),
    sa.Column('resposta_corpo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_chave_idempotencia_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chave_idempotencia')),
    sa.UniqueConstraint('chave', name=op.f('uq_chave_idempotencia_chave'))
    )
    op.create_index('ix_chave_idempotencia_criado_em', 'chave_idempotencia', ['criado_em'], unique=False)
    op.create_table('dispositivo',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=True),
    sa.Column('install_id', sa.String(length=64), nullable=False),
    sa.Column('modelo', sa.Text(), nullable=True),
    sa.Column('versao_so', sa.Text(), nullable=True),
    sa.Column('versao_app', sa.Text(), nullable=True),
    sa.Column('pilha_nfc', sa.String(length=16), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('primeiro_acesso_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_acesso_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_dispositivo_empresa_id')),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], name=op.f('fk_dispositivo_registrado_por')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispositivo')),
    sa.UniqueConstraint('empresa_id', 'install_id', name='uq_dispositivo_empresa_install')
    )
    op.create_index('ix_dispositivo_ativo', 'dispositivo', ['ativo'], unique=False, postgresql_where=sa.text('ativo IS true'))
    op.create_table('remessa',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('empresa_embarcador_id', sa.UUID(), nullable=False),
    sa.Column('empresa_transportadora_id', sa.UUID(), nullable=True),
    sa.Column('identidade_documento', sa.String(length=96), nullable=True),
    sa.Column('destinatario_nome', sa.Text(), nullable=False),
    sa.Column('destinatario_cnpj', sa.String(length=14), nullable=True),
    sa.Column('destinatario_endereco', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('destinatario_contato', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('perfil_termico_id', sa.UUID(), nullable=False),
    sa.Column('intervalo_segundos', sa.Integer(), server_default='600', nullable=False),
    sa.Column('previsao_coleta_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previsao_entrega_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('descricao_carga', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('preparacao', 'aguardando_aceite', 'aguardando_coleta', 'em_transporte', 'entregue_aguardando_leitura', 'concluida', 'cancelada', name='status_remessa'), server_default='preparacao', nullable=False),
    sa.Column('criada_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criada_por'], ['usuario.id'], name=op.f('fk_remessa_criada_por')),
    sa.ForeignKeyConstraint(['empresa_embarcador_id'], ['empresa.id'], name=op.f('fk_remessa_empresa_embarcador_id')),
    sa.ForeignKeyConstraint(['empresa_transportadora_id'], ['empresa.id'], name=op.f('fk_remessa_empresa_transportadora_id')),
    sa.ForeignKeyConstraint(['perfil_termico_id'], ['perfil_termico.id'], name=op.f('fk_remessa_perfil_termico_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remessa')),
    sa.UniqueConstraint('empresa_embarcador_id', 'codigo', name='uq_remessa_embarcador_codigo'),
    sa.UniqueConstraint('identidade_documento', name=op.f('uq_remessa_identidade_documento'))
    )
    op.create_index('ix_remessa_atualizado_em', 'remessa', ['atualizado_em'], unique=False)
    op.create_index('ix_remessa_embarcador_criado', 'remessa', ['empresa_embarcador_id', 'criado_em'], unique=False)
    op.create_index('ix_remessa_transportadora_status', 'remessa', ['empresa_transportadora_id', 'status'], unique=False)
    op.create_table('token_recuperacao',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_token_recuperacao_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_recuperacao')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_token_recuperacao_token_hash'))
    )
    op.create_index('ix_token_recuperacao_usuario_id', 'token_recuperacao', ['usuario_id'], unique=False)
    op.create_table('documento',
    sa.Column('remessa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('nfe', 'nfce', 'cte', 'cte_os', 'mdfe', 'awb', 'pedido', 'outro', 'sem_documento', name='tipo_documento'), nullable=False),
    sa.Column('numero', sa.String(length=64), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('cnpj_emitente', sa.String(length=14), nullable=True),
    sa.Column('serie', sa.String(length=8), nullable=True),
    sa.Column('uf_emitente', sa.String(length=2), nullable=True),
    sa.Column('competencia', sa.String(length=7), nullable=True),
    sa.Column('conteudo_bruto', sa.Text(), nullable=True),
    sa.Column('simbologia', sa.String(length=24), nullable=True),
    sa.Column('digitado_manualmente', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('validado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('observacao_validacao', sa.Text(), nullable=True),
    sa.Column('lido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remessa_id'], ['remessa.id'], name=op.f('fk_documento_remessa_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documento'))
    )
    op.create_index('ix_documento_chave_acesso', 'documento', ['chave_acesso'], unique=False)
    op.create_index('ix_documento_remessa_id', 'documento', ['remessa_id'], unique=False)
    op.create_table('evento_custodia',
    sa.Column('remessa_id', sa.UUID(), nullable=False),
    sa.Column('de_parte', sa.Enum('embarcador', 'transportadora', 'destinatario', name='parte_custodia'), nullable=True),
    sa.Column('para_parte', sa.Enum('embarcador', 'transportadora', 'destinatario', name='parte_custodia'), nullable=False),
    sa.Column('de_empresa_id', sa.UUID(), nullable=True),
    sa.Column('para_empresa_id', sa.UUID(), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispositivo_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origem', sa.Enum('automatico_nfc', 'confirmado_tempo_real', 'informado_posteriormente', name='origem_evento'), nullable=False),
    sa.Column('volumes_confirmados', sa.Integer(), nullable=True),
    sa.Column('recebedor', sa.Text(), nullable=True),
    sa.Column('evidencia_arquivo_id', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.UUID(), nullable=True),
    sa.Column('dispositivo_id', sa.UUID(), nullable=True),
    sa.Column('geo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['de_empresa_id'], ['empresa.id'], name=op.f('fk_evento_custodia_de_empresa_id')),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], name=op.f('fk_evento_custodia_dispositivo_id')),
    sa.ForeignKeyConstraint(['evidencia_arquivo_id'], ['arquivo.id'], name=op.f('fk_evento_custodia_evidencia_arquivo_id')),
    sa.ForeignKeyConstraint(['para_empresa_id'], ['empresa.id'], name=op.f('fk_evento_custodia_para_empresa_id')),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], name=op.f('fk_evento_custodia_registrado_por')),
    sa.ForeignKeyConstraint(['remessa_id'], ['remessa.id'], name=op.f('fk_evento_custodia_remessa_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento_custodia'))
    )
    op.create_index('ix_evento_custodia_remessa_ocorrido', 'evento_custodia', ['remessa_id', 'ocorrido_em'], unique=False)
    op.create_table('laudo',
    sa.Column('remessa_id', sa.UUID(), nullable=False),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('gerado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gerado_por', sa.UUID(), nullable=True),
    sa.Column('versao_regra', sa.String(length=32), nullable=False),
    sa.Column('versao_decodificador', sa.String(length=64), nullable=False),
    sa.Column('veredito', sa.Enum('conforme', 'alerta', 'excursao', 'inconclusivo', name='veredito_laudo'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_sha256', sa.LargeBinary(), nullable=False),
    sa.Column('codigo_verificacao', sa.String(length=24), nullable=False),
    sa.Column('arquivo_xlsx_id', sa.UUID(), nullable=True),
    sa.Column('arquivo_pdf_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_pdf_id'], ['arquivo.id'], name=op.f('fk_laudo_arquivo_pdf_id')),
    sa.ForeignKeyConstraint(['arquivo_xlsx_id'], ['arquivo.id'], name=op.f('fk_laudo_arquivo_xlsx_id')),
    sa.ForeignKeyConstraint(['gerado_por'], ['usuario.id'], name=op.f('fk_laudo_gerado_por')),
    sa.ForeignKeyConstraint(['remessa_id'], ['remessa.id'], name=op.f('fk_laudo_remessa_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laudo')),
    sa.UniqueConstraint('codigo_verificacao', name=op.f('uq_laudo_codigo_verificacao')),
    sa.UniqueConstraint('remessa_id', 'versao', name='uq_laudo_remessa_versao')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('dispositivo_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.String(length=64), nullable=False),
    sa.Column('entidade', sa.String(length=64), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], name=op.f('fk_log_auditoria_dispositivo_id')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_log_auditoria_empresa_id')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_log_auditoria_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_auditoria'))
    )
    op.create_index('ix_log_auditoria_em', 'log_auditoria', ['em'], unique=False)
    op.create_index('ix_log_auditoria_entidade', 'log_auditoria', ['entidade', 'entidade_id', 'em'], unique=False)
    op.create_table('lote_etiqueta',
    sa.Column('fornecedor', sa.Text(), nullable=False),
    sa.Column('ordem_compra', sa.Text(), nullable=True),
    sa.Column('modelo_hardware', sa.Text(), nullable=False),
    sa.Column('part_number_ci', sa.Text(), nullable=True),
    sa.Column('fabricante_ci', sa.Text(), nullable=True),
    sa.Column('mapa_comandos', sa.String(length=32), nullable=True),
    sa.Column('fabricado_em', sa.Date(), nullable=True),
    sa.Column('recebido_em', sa.Date(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('certificado_ref', sa.Text(), nullable=True),
    sa.Column('certificado_arquivo_id', sa.UUID(), nullable=True),
    sa.Column('pontos_calibracao_c', postgresql.ARRAY(sa.Numeric(precision=5, scale=2)), nullable=True),
    sa.Column('incerteza_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calibracao_valida_ate', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_lote_etiqueta_quantidade_positiva')),
    sa.ForeignKeyConstraint(['certificado_arquivo_id'], ['arquivo.id'], name=op.f('fk_lote_etiqueta_certificado_arquivo_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lote_etiqueta'))
    )
    op.create_table('sessao_auth',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('dispositivo_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('familia_id', sa.UUID(), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], name=op.f('fk_sessao_auth_dispositivo_id')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_sessao_auth_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessao_auth')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessao_auth_token_hash'))
    )
    op.create_index('ix_sessao_auth_familia_id', 'sessao_auth', ['familia_id'], unique=False)
    op.create_index('ix_sessao_auth_usuario_id', 'sessao_auth', ['usuario_id'], unique=False)
    op.create_index('ix_sessao_auth_vigentes', 'sessao_auth', ['expira_em'], unique=False, postgresql_where=sa.text('revogada_em IS NULL'))
    op.create_table('volume',
    sa.Column('remessa_id', sa.UUID(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('identidade', sa.String(length=110), nullable=True),
    sa.Column('codigo_externo', sa.String(length=64), nullable=True),
    sa.Column('codigo_externo_bruto', sa.Text(), nullable=True),
    sa.Column('monitorado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('sem_etiqueta', 'vinculado', 'monitorando', 'encerrado', name='status_volume'), server_default='sem_etiqueta', nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remessa_id'], ['remessa.id'], name=op.f('fk_volume_remessa_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volume')),
    sa.UniqueConstraint('remessa_id', 'sequencia', name='uq_volume_remessa_sequencia')
    )
    op.create_index('ix_volume_remessa_id', 'volume', ['remessa_id'], unique=False)
    op.create_table('etiqueta',
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('nfc_uid', sa.String(length=32), nullable=False),
    sa.Column('uhf_epc', sa.String(length=64), nullable=True),
    sa.Column('uhf_tid', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.Enum('estoque', 'vinculada', 'monitorando', 'lida', 'manutencao', 'aposentada', name='estado_etiqueta'), server_default='estoque', nullable=False),
    sa.Column('ciclos_ativacao', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ultima_tensao_v', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ultima_tensao_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aposentada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aposentada_motivo', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_etiqueta_empresa_id')),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_etiqueta.id'], name=op.f('fk_etiqueta_lote_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etiqueta')),
    sa.UniqueConstraint('nfc_uid', name=op.f('uq_etiqueta_nfc_uid')),
    sa.UniqueConstraint('qr_payload', name=op.f('uq_etiqueta_qr_payload')),
    sa.UniqueConstraint('serial', name=op.f('uq_etiqueta_serial'))
    )
    op.create_index('ix_etiqueta_atualizado_em', 'etiqueta', ['atualizado_em'], unique=False)
    op.create_index('ix_etiqueta_em_uso', 'etiqueta', ['estado'], unique=False, postgresql_where=sa.text("estado != 'aposentada'"))
    op.create_index('ix_etiqueta_empresa_id', 'etiqueta', ['empresa_id'], unique=False)
    op.create_table('vinculo_etiqueta',
    sa.Column('volume_id', sa.UUID(), nullable=False),
    sa.Column('etiqueta_id', sa.UUID(), nullable=False),
    sa.Column('vinculada_por', sa.UUID(), nullable=True),
    sa.Column('dispositivo_id', sa.UUID(), nullable=True),
    sa.Column('qr_escaneado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uid_conferiu', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('liberada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_liberacao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], name=op.f('fk_vinculo_etiqueta_dispositivo_id')),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiqueta.id'], name=op.f('fk_vinculo_etiqueta_etiqueta_id')),
    sa.ForeignKeyConstraint(['vinculada_por'], ['usuario.id'], name=op.f('fk_vinculo_etiqueta_vinculada_por')),
    sa.ForeignKeyConstraint(['volume_id'], ['volume.id'], name=op.f('fk_vinculo_etiqueta_volume_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vinculo_etiqueta'))
    )
    op.create_index('ix_vinculo_etiqueta_volume_id', 'vinculo_etiqueta', ['volume_id'], unique=False)
    op.create_index('uq_vinculo_etiqueta_ativo', 'vinculo_etiqueta', ['etiqueta_id'], unique=True, postgresql_where=sa.text('liberada_em IS NULL'))
    op.create_table('sessao_monitoramento',
    sa.Column('etiqueta_id', sa.UUID(), nullable=False),
    sa.Column('vinculo_id', sa.UUID(), nullable=False),
    sa.Column('remessa_id', sa.UUID(), nullable=False),
    sa.Column('perfil_termico_id', sa.UUID(), nullable=False),
    sa.Column('epoch_inicio_etiqueta', sa.BigInteger(), nullable=False),
    sa.Column('inicio_dispositivo_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inicio_servidor_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('desvio_relogio_ms', sa.BigInteger(), nullable=True),
    sa.Column('referencia_relogio', sa.String(length=16), nullable=True),
    sa.Column('base_de_tempo', sa.Enum('instante_start', 'primeira_janela', name='base_de_tempo'), server_default='instante_start', nullable=False),
    sa.Column('plataforma_ativacao', sa.Enum('android', 'ios', name='plataforma'), nullable=True),
    sa.Column('delay_minutos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('intervalo_segundos', sa.Integer(), nullable=False),
    sa.Column('quantidade_planejada', sa.Integer(), nullable=False),
    sa.Column('min_configurado_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_configurado_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('modo_armazenamento', sa.SmallInteger(), nullable=True),
    sa.Column('ativacao_confirmada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ativacao_confirmada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativada_por', sa.UUID(), nullable=True),
    sa.Column('dispositivo_id', sa.UUID(), nullable=True),
    sa.Column('tensao_no_start_v', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('verificado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registrando_na_verificacao', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ativa', 'encerrada_normal', 'encerrada_anormal', 'abandonada', name='status_sessao'), server_default='ativa', nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('intervalo_segundos BETWEEN 1 AND 65535', name=op.f('ck_sessao_monitoramento_intervalo_valido')),
    sa.CheckConstraint('min_configurado_c < max_configurado_c', name=op.f('ck_sessao_monitoramento_faixa_coerente')),
    sa.ForeignKeyConstraint(['ativada_por'], ['usuario.id'], name=op.f('fk_sessao_monitoramento_ativada_por')),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], name=op.f('fk_sessao_monitoramento_dispositivo_id')),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiqueta.id'], name=op.f('fk_sessao_monitoramento_etiqueta_id')),
    sa.ForeignKeyConstraint(['perfil_termico_id'], ['perfil_termico.id'], name=op.f('fk_sessao_monitoramento_perfil_termico_id')),
    sa.ForeignKeyConstraint(['remessa_id'], ['remessa.id'], name=op.f('fk_sessao_monitoramento_remessa_id')),
    sa.ForeignKeyConstraint(['vinculo_id'], ['vinculo_etiqueta.id'], name=op.f('fk_sessao_monitoramento_vinculo_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessao_monitoramento')),
    sa.UniqueConstraint('etiqueta_id', 'epoch_inicio_etiqueta', name='uq_sessao_etiqueta_epoch')
    )
    op.create_index('ix_sessao_monitoramento_ativas', 'sessao_monitoramento', ['status'], unique=False, postgresql_where=sa.text("status = 'ativa'"))
    op.create_index('ix_sessao_monitoramento_remessa_id', 'sessao_monitoramento', ['remessa_id'], unique=False)
    op.create_table('leitura_etiqueta',
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('etiqueta_id', sa.UUID(), nullable=False),
    sa.Column('chave_idempotencia', sa.String(length=160), nullable=False),
    sa.Column('tipo_leitura', sa.Enum('ativacao', 'checkpoint', 'final', name='tipo_leitura'), nullable=False),
    sa.Column('dispositivo_id', sa.UUID(), nullable=True),
    sa.Column('lida_por', sa.UUID(), nullable=True),
    sa.Column('lida_em_dispositivo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recebida_em_servidor', sa.DateTime(timezone=True), nullable=False),
    sa.Column('desvio_relogio_ms', sa.BigInteger(), nullable=True),
    sa.Column('resposta_bruta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memoria_bruta_hex', sa.Text(), nullable=True),
    sa.Column('versao_sdk', sa.String(length=64), nullable=True),
    sa.Column('versao_decodificador', sa.String(length=64), nullable=False),
    sa.Column('codigo_estado', sa.String(length=8), nullable=True),
    sa.Column('quantidade_planejada_relatada', sa.Integer(), nullable=True),
    sa.Column('quantidade_medida', sa.Integer(), nullable=True),
    sa.Column('intervalo_relatado_s', sa.Integer(), nullable=True),
    sa.Column('delay_relatado_min', sa.Integer(), nullable=True),
    sa.Column('tensao_v', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('temperatura_instantanea_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bateria_ok', sa.Boolean(), nullable=True),
    sa.Column('deriva_rtc_segundos', sa.BigInteger(), nullable=True),
    sa.Column('horarios_corrigidos', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hash_payload', sa.LargeBinary(), nullable=False),
    sa.Column('hash_anterior', sa.LargeBinary(), nullable=True),
    sa.Column('hash_encadeado', sa.LargeBinary(), nullable=False),
    sa.Column('ip_origem', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], name=op.f('fk_leitura_etiqueta_dispositivo_id')),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiqueta.id'], name=op.f('fk_leitura_etiqueta_etiqueta_id')),
    sa.ForeignKeyConstraint(['lida_por'], ['usuario.id'], name=op.f('fk_leitura_etiqueta_lida_por')),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao_monitoramento.id'], name=op.f('fk_leitura_etiqueta_sessao_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leitura_etiqueta')),
    sa.UniqueConstraint('chave_idempotencia', name=op.f('uq_leitura_etiqueta_chave_idempotencia')),
    sa.UniqueConstraint('sessao_id', 'hash_payload', name='uq_leitura_sessao_hash')
    )
    op.create_index('ix_leitura_etiqueta_sessao_lida', 'leitura_etiqueta', ['sessao_id', 'lida_em_dispositivo'], unique=False)
    op.create_table('excursao',
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('leitura_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('acima', 'abaixo', name='tipo_excursao'), nullable=False),
    sa.Column('gravidade', sa.Enum('alerta', 'acao', 'critica', name='gravidade'), nullable=False),
    sa.Column('inicio_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracao_segundos', sa.Integer(), nullable=False),
    sa.Column('quantidade_pontos', sa.Integer(), nullable=False),
    sa.Column('pico_c', sa.REAL(), nullable=False),
    sa.Column('limite_c', sa.REAL(), nullable=False),
    sa.Column('indice_primeira_amostra', sa.Integer(), nullable=False),
    sa.Column('versao_regra', sa.String(length=32), nullable=False),
    sa.Column('avaliada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('substituida_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fim_em >= inicio_em', name=op.f('ck_excursao_intervalo_coerente')),
    sa.ForeignKeyConstraint(['leitura_id'], ['leitura_etiqueta.id'], name=op.f('fk_excursao_leitura_id')),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao_monitoramento.id'], name=op.f('fk_excursao_sessao_id')),
    sa.ForeignKeyConstraint(['substituida_por'], ['excursao.id'], name=op.f('fk_excursao_substituida_por')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_excursao'))
    )
    op.create_index('ix_excursao_sessao_vigente', 'excursao', ['sessao_id'], unique=False, postgresql_where=sa.text('substituida_por IS NULL'))
    op.create_table('serie_medicao',
    sa.Column('leitura_id', sa.UUID(), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('primeiro_ponto_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intervalo_segundos', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('temperaturas_c', postgresql.ARRAY(sa.REAL()), nullable=False),
    sa.Column('bits_campo', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('min_c', sa.REAL(), nullable=True),
    sa.Column('max_c', sa.REAL(), nullable=True),
    sa.Column('media_c', sa.REAL(), nullable=True),
    sa.Column('mkt_c', sa.REAL(), nullable=True),
    sa.Column('tor_abaixo_s', sa.Integer(), nullable=True),
    sa.Column('tor_acima_s', sa.Integer(), nullable=True),
    sa.Column('maior_excursao_s', sa.Integer(), nullable=True),
    sa.Column('versao_regra', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade = cardinality(temperaturas_c)', name=op.f('ck_serie_medicao_quantidade_bate_com_array')),
    sa.ForeignKeyConstraint(['leitura_id'], ['leitura_etiqueta.id'], name=op.f('fk_serie_medicao_leitura_id')),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao_monitoramento.id'], name=op.f('fk_serie_medicao_sessao_id')),
    sa.PrimaryKeyConstraint('leitura_id', name=op.f('pk_serie_medicao'))
    )
    op.create_index('ix_serie_medicao_sessao_id', 'serie_medicao', ['sessao_id'], unique=False)
    op.create_table('ocorrencia',
    sa.Column('remessa_id', sa.UUID(), nullable=False),
    sa.Column('volume_id', sa.UUID(), nullable=True),
    sa.Column('sessao_id', sa.UUID(), nullable=True),
    sa.Column('excursao_id', sa.UUID(), nullable=True),
    sa.Column('chave_natural', sa.String(length=128), nullable=False),
    sa.Column('tipo', sa.Enum('termica', 'avaria', 'atraso', 'volume_faltante', 'divergencia_documental', 'etiqueta_inativa', 'bateria_baixa', 'outra', name='tipo_ocorrencia'), nullable=False),
    sa.Column('gravidade', sa.Enum('alerta', 'acao', 'critica', name='gravidade'), nullable=True),
    sa.Column('status', sa.Enum('aberta', 'alerta_enviado', 'em_tratamento', 'resolvida', 'sem_acao', name='status_ocorrencia'), server_default='aberta', nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detectado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pico_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('limite_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duracao_segundos', sa.BigInteger(), nullable=True),
    sa.Column('versao_regra', sa.String(length=32), nullable=False),
    sa.Column('alerta_enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerta_canal', sa.String(length=24), nullable=True),
    sa.Column('fechada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aberta_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aberta_por'], ['usuario.id'], name=op.f('fk_ocorrencia_aberta_por')),
    sa.ForeignKeyConstraint(['excursao_id'], ['excursao.id'], name=op.f('fk_ocorrencia_excursao_id')),
    sa.ForeignKeyConstraint(['remessa_id'], ['remessa.id'], name=op.f('fk_ocorrencia_remessa_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao_monitoramento.id'], name=op.f('fk_ocorrencia_sessao_id')),
    sa.ForeignKeyConstraint(['volume_id'], ['volume.id'], name=op.f('fk_ocorrencia_volume_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocorrencia')),
    sa.UniqueConstraint('chave_natural', name=op.f('uq_ocorrencia_chave_natural'))
    )
    op.create_index('ix_ocorrencia_remessa_ocorrido', 'ocorrencia', ['remessa_id', 'ocorrido_em'], unique=False)
    op.create_index('ix_ocorrencia_status', 'ocorrencia', ['status'], unique=False)
    op.create_table('acao_corretiva',
    sa.Column('ocorrencia_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('troca_refrigerante', 'reacondicionamento', 'camara_fria', 'troca_embalagem', 'cliente_comunicado', 'transporte_recusado', 'produto_segregado', 'nenhuma', 'outra', name='tipo_acao_corretiva'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origem', sa.Enum('automatico_nfc', 'confirmado_tempo_real', 'informado_posteriormente', name='origem_evento'), nullable=False),
    sa.Column('executada_por_nome', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('evidencia_arquivo_id', sa.UUID(), nullable=True),
    sa.Column('registrada_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_acao_corretiva_empresa_id')),
    sa.ForeignKeyConstraint(['evidencia_arquivo_id'], ['arquivo.id'], name=op.f('fk_acao_corretiva_evidencia_arquivo_id')),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencia.id'], name=op.f('fk_acao_corretiva_ocorrencia_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrada_por'], ['usuario.id'], name=op.f('fk_acao_corretiva_registrada_por')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acao_corretiva'))
    )
    op.create_index('ix_acao_corretiva_ocorrencia_id', 'acao_corretiva', ['ocorrencia_id'], unique=False)
    op.create_table('envio_alerta',
    sa.Column('ocorrencia_id', sa.UUID(), nullable=False),
    sa.Column('destinatario_email', sa.String(length=320), nullable=False),
    sa.Column('assunto', sa.Text(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('provedor', sa.String(length=32), nullable=True),
    sa.Column('provedor_mensagem_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('fila', 'enviado', 'falha', 'descartado', name='status_envio'), server_default='fila', nullable=False),
    sa.Column('tentativas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ultimo_erro', sa.Text(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencia.id'], name=op.f('fk_envio_alerta_ocorrencia_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_envio_alerta'))
    )
    op.create_index('ix_envio_alerta_ocorrencia_id', 'envio_alerta', ['ocorrencia_id'], unique=False)
    op.create_index('ix_envio_alerta_pendentes', 'envio_alerta', ['status'], unique=False, postgresql_where=sa.text("status = 'fila'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_envio_alerta_pendentes', table_name='envio_alerta', postgresql_where=sa.text("status = 'fila'"))
    op.drop_index('ix_envio_alerta_ocorrencia_id', table_name='envio_alerta')
    op.drop_table('envio_alerta')
    op.drop_index('ix_acao_corretiva_ocorrencia_id', table_name='acao_corretiva')
    op.drop_table('acao_corretiva')
    op.drop_index('ix_ocorrencia_status', table_name='ocorrencia')
    op.drop_index('ix_ocorrencia_remessa_ocorrido', table_name='ocorrencia')
    op.drop_table('ocorrencia')
    op.drop_index('ix_serie_medicao_sessao_id', table_name='serie_medicao')
    op.drop_table('serie_medicao')
    op.drop_index('ix_excursao_sessao_vigente', table_name='excursao', postgresql_where=sa.text('substituida_por IS NULL'))
    op.drop_table('excursao')
    op.drop_index('ix_leitura_etiqueta_sessao_lida', table_name='leitura_etiqueta')
    op.drop_table('leitura_etiqueta')
    op.drop_index('ix_sessao_monitoramento_remessa_id', table_name='sessao_monitoramento')
    op.drop_index('ix_sessao_monitoramento_ativas', table_name='sessao_monitoramento', postgresql_where=sa.text("status = 'ativa'"))
    op.drop_table('sessao_monitoramento')
    op.drop_index('uq_vinculo_etiqueta_ativo', table_name='vinculo_etiqueta', postgresql_where=sa.text('liberada_em IS NULL'))
    op.drop_index('ix_vinculo_etiqueta_volume_id', table_name='vinculo_etiqueta')
    op.drop_table('vinculo_etiqueta')
    op.drop_index('ix_etiqueta_empresa_id', table_name='etiqueta')
    op.drop_index('ix_etiqueta_em_uso', table_name='etiqueta', postgresql_where=sa.text("estado != 'aposentada'"))
    op.drop_index('ix_etiqueta_atualizado_em', table_name='etiqueta')
    op.drop_table('etiqueta')
    op.drop_index('ix_volume_remessa_id', table_name='volume')
    op.drop_table('volume')
    op.drop_index('ix_sessao_auth_vigentes', table_name='sessao_auth', postgresql_where=sa.text('revogada_em IS NULL'))
    op.drop_index('ix_sessao_auth_usuario_id', table_name='sessao_auth')
    op.drop_index('ix_sessao_auth_familia_id', table_name='sessao_auth')
    op.drop_table('sessao_auth')
    op.drop_table('lote_etiqueta')
    op.drop_index('ix_log_auditoria_entidade', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_em', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_table('laudo')
    op.drop_index('ix_evento_custodia_remessa_ocorrido', table_name='evento_custodia')
    op.drop_table('evento_custodia')
    op.drop_index('ix_documento_remessa_id', table_name='documento')
    op.drop_index('ix_documento_chave_acesso', table_name='documento')
    op.drop_table('documento')
    op.drop_index('ix_token_recuperacao_usuario_id', table_name='token_recuperacao')
    op.drop_table('token_recuperacao')
    op.drop_index('ix_remessa_transportadora_status', table_name='remessa')
    op.drop_index('ix_remessa_embarcador_criado', table_name='remessa')
    op.drop_index('ix_remessa_atualizado_em', table_name='remessa')
    op.drop_table('remessa')
    op.drop_index('ix_dispositivo_ativo', table_name='dispositivo', postgresql_where=sa.text('ativo IS true'))
    op.drop_table('dispositivo')
    op.drop_index('ix_chave_idempotencia_criado_em', table_name='chave_idempotencia')
    op.drop_table('chave_idempotencia')
    op.drop_index('ix_arquivo_sha256', table_name='arquivo')
    op.drop_index('ix_arquivo_empresa_categoria', table_name='arquivo')
    op.drop_table('arquivo')
    op.drop_index('ix_usuario_empresa_id', table_name='usuario')
    op.drop_table('usuario')
    op.drop_index('ix_perfil_termico_empresa_id', table_name='perfil_termico')
    op.drop_table('perfil_termico')
    op.drop_table('destinatario_alerta')
    op.drop_index('ix_empresa_ativa', table_name='empresa', postgresql_where=sa.text('ativa IS true'))
    op.drop_table('empresa')
    # ### end Alembic commands ###
